### ISSUE TITLE
Migrate docs to main repo

### ISSUE THREAD

**Issue by 0xTim** [mattesmohr/docs-de#4]
We've [just launched](https://blog.vapor.codes/posts/documentation-changes/) real localisation support for the main documentation site to allow us to support any language required. Could you migrate the translated pages over to their respective pages in the main site, as described [in the README](https://github.com/vapor/docs#translating)?

Once we've done that we can archive this repo

**Comment by mattesmohr** [comment]
Yes, could do. I will transmit it in the upcoming days. 👍🏻

**Comment by mattesmohr** [comment]
@0xTim I have done all the transmissions into my fork of vapor/docs. Technically you can begin to archive the repository. But I think there is no need to archive this repository. We could just delete it, don't you think?

**Comment by 0xTim** [comment]
@mattesmohr Great! Want to open a PR? In terms of archiving, I don't think there's any disadvantage to doing it and it doesn't cost us anything so why not. We can just update the README to point to the main docs

**Comment by mattesmohr** [comment]
@0xTim  Sure, but I think you have to guide me through. Cause you and Benny did changes the last two days, so my fork is a few commits behind.

I guess I have to fetch the changes from upstream to my origin, solve conflicts and after that, request it to the upstream? May I right?

**Comment by 0xTim** [comment]
@mattesmohr Want to add me as a collaborator to the fork and I can take a look. It's probably just some rearranging

**Comment by mattesmohr** [comment]
> @mattesmohr Want to add me as a collaborator to the fork and I can take a look. It's probably just some rearranging

Done. I am online in the voice channel, if I can help.

**Comment by 0xTim** [comment]
Closing as this is solved in https://github.com/vapor/docs/pull/662
